name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # сюда добавьте ваши шаги сборки/тестов/публикации
      - name: Say hello
        run: echo "CI triggered on ${{ github.ref }}"
