name: Build & Push to OCIR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to OCIR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.OCIR_URL }}
          username: ${{ secrets.OCIR_USERNAME }}
          password: ${{ secrets.OCIR_AUTH_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.OCIR_URL }}/${{ secrets.OCIR_NAMESPACE }}/${{ secrets.OCIR_REPO }}:latest
            ${{ secrets.OCIR_URL }}/${{ secrets.OCIR_NAMESPACE }}/${{ secrets.OCIR_REPO }}:${{ github.sha }}

      - name: Show image reference
        run: |
          echo "Pushed:"
          echo "${{ secrets.OCIR_URL }}/${{ secrets.OCIR_NAMESPACE }}/${{ secrets.OCIR_REPO }}:latest"
          echo "${{ secrets.OCIR_URL }}/${{ secrets.OCIR_NAMESPACE }}/${{ secrets.OCIR_REPO }}:${GITHUB_SHA}"
